### PR TITLE
refactor: #53 remove hpc-specific libraries to use single version

### LINKED ISSUE #53: Remove umbridge.h copy in hpc setup
Remove `hpc/lib/*` and use change load balancer to use `lib/umbridge.h` instead. The latter should now have all the necessary features (disabling error checks, optional parallel model evaluations).

### PR DESCRIPTION
**Pull request by Crambor**
Resolves #53 - only merge after PR #54 is merged first.

### CODE REVIEW

**Comment by linusseelinger** [comment]
@Schlevidon Could you give this a quick test run? Most importantly, the load balancer should have error checks disabled and should still submit model evaluation jobs in parallel.

**Review by linusseelinger — APPROVED** [review]
Looks good to me! Adapted LoadBalancer.cpp to the new umbridge.h path and serveModels arguments.

Once @Schlevidon confirms it's still working as intended, let's merge!

**Comment by Schlevidon** [comment]
Did a few test runs using the minimal example with single and parallel requests. Didn't notice any issues and as far as I can tell parallel evaluations work properly. Error checks seem to be disabled (as intended), since I get exactly one HQ job per evaluation request. 

Should be good to go! 👍

**Comment by linusseelinger** [comment]
Looks good, thanks @Crambor @Schlevidon !

**Pull request merged**
